version: "3"
services:
  ftp:
    env_file: ftp.env
    image: bogem/ftp
    volumes:
      - /mnt/data/openftp:/home/vsftpd
    ports:
      - "20:20"
      - "21:21"
      - "47400-47470:47400-47470"
    container_name: FTPServer
    hostname: FTPServer
    restart: unless-stopped
    networks:
      - vmnw
networks:
  vmnw:
    external:
      name: vm_nw
